source "http://rubygems.org"
gem 'httparty'
gem 'rails', '3.2.8'
gem 'json'

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
  gem "rspec", "~> 2.8.0"
  gem "rdoc", "~> 3.12"
  gem "bundler"
  gem "jeweler", "~> 1.8.4"
  gem "simplecov"
end

group :test do
  gem 'webmock'
  gem 'vcr'
end